/*
 Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function g(a){return CKEDITOR.tools.capitalize(a,!0)}function n(a,b){function c(a){return function(c,d){var b=c.widgets.focused,e=CKEDITOR.TRISTATE_DISABLED;b&&"easyimage"===b.name&&(e=a&&a.call(this,b,c,d)?CKEDITOR.TRISTATE_ON:CKEDITOR.TRISTATE_OFF);this.setState(e)}}function e(a,b,d,f){d.type="widget";d.widget="easyimage";d.group=d.group||"easyimage";d.element="figure";b=new CKEDITOR.style(d);a.filter.allow(b);b=new CKEDITOR.styleCommand(b);b.contextSensitive=!0;b.refresh=c(function(a,
b,c){return this.style.checkActive(c,b)});a.addCommand(f,b);b=a.getCommand(f);b.enable=function(){};b.refresh(a,a.elementPath());return b}a.addCommand("easyimageAlt",new CKEDITOR.dialogCommand("easyimageAlt",{startDisabled:!0,contextSensitive:!0,refresh:c()}));(function(b){function c(a,b){var d=a.match(/^easyimage(.+)$/);if(d){var e=(d[1][0]||"").toLowerCase()+d[1].substr(1);if(d[1]in b)return d[1];if(e in b)return e}return null}a.on("afterCommandExec",function(d){c(d.data.name,b)&&(a.forceNextSelectionCheck(),
a.selectionChange(!0))});a.on("beforeCommandExec",function(d){c(d.data.name,b)&&d.data.command.style.checkActive(d.editor.elementPath(),a)&&(d.cancel(),a.focus())});for(var d in b)e(a,d,b[d],"easyimage"+g(d))})(b)}function p(a){var b=a.config.easyimage_toolbar;a.plugins.contextmenu&&(b.split&&(b=b.split(",")),a.addMenuGroup("easyimage"),CKEDITOR.tools.array.forEach(b,function(b){b=a.ui.items[b];a.addMenuItem(b.name,{label:b.label,command:b.command,group:"easyimage"})}))}function q(a){var b=a.sender.editor,
c=b.config.easyimage_toolbar;c.split&&(c=c.split(","));CKEDITOR.tools.array.forEach(c,function(c){c=b.ui.items[c];a.data[c.name]=b.getCommand(c.command).state})}function r(a,b){var c=a.config,e=c.easyimage_class,c={name:"easyimage",allowedContent:{figure:{classes:c.easyimage_sideClass},img:{attributes:"!src,srcset,alt,width,sizes"}},requiredContent:"figure; img[!src]",styleableElements:"figure",supportedTypes:/image\/(jpeg|png|gif|bmp)/,loaderType:CKEDITOR.plugins.cloudservices.cloudServicesLoader,
progressReporterType:CKEDITOR.plugins.imagebase.progressBar,upcasts:{figure:function(a){if((!e||a.hasClass(e))&&1===a.find("img",!0).length)return a}},init:function(){function b(a,c){var e=a.$;if(e.complete&&e.naturalWidth)return c(e.naturalWidth);a.once("load",function(){c(e.naturalWidth)})}var c=this.parts.image;c&&!c.$.complete&&b(c,function(){var b=a._.easyImageToolbarContext.toolbar._view;b.rect.visible&&b.attach(b._pointedElement,{focusElement:!1})});c=this.element.data("cke-upload-id");"undefined"!==
typeof c&&(this.setData("uploadId",c),this.element.data("cke-upload-id",!1));this.on("contextMenu",q);a.config.easyimage_class&&this.addClass(a.config.easyimage_class);this.on("uploadStarted",function(){var a=this;b(a.parts.image,function(b){a.parts.image.hasAttribute("width")||(a.editor.fire("lockSnapshot"),a.parts.image.setAttribute("width",b),a.editor.fire("unlockSnapshot"))})});this.on("uploadDone",function(a){a=a.data.loader.responseData.response;var b=CKEDITOR.plugins.easyimage._parseSrcSet(a);
this.parts.image.setAttributes({"data-cke-saved-src":a["default"],src:a["default"],srcset:b,sizes:"100vw"})});this.on("uploadFailed",function(){alert(this.editor.lang.easyimage.uploadFailed)});this._loadDefaultStyle()},_loadDefaultStyle:function(){var c=!1,e=a.config.easyimage_defaultStyle,d;for(d in b){var f=a.getCommand("easyimage"+g(d));!c&&f&&f.style&&-1!==CKEDITOR.tools.array.indexOf(f.style.group,"easyimage")&&this.checkStyleActive(f.style)&&(c=!0)}!c&&e&&a.getCommand("easyimage"+g(e))&&this.applyStyle(a.getCommand("easyimage"+
g(e)).style)}};e&&(c.requiredContent+="(!"+e+")",c.allowedContent.figure.classes="!"+e+","+c.allowedContent.figure.classes);a.plugins.link&&(c=CKEDITOR.plugins.imagebase.addFeature(a,"link",c));c=CKEDITOR.plugins.imagebase.addFeature(a,"upload",c);c=CKEDITOR.plugins.imagebase.addFeature(a,"caption",c);CKEDITOR.plugins.imagebase.addImageWidget(a,"easyimage",c)}function t(a){a.on("paste",function(b){if(!a.isReadOnly&&b.data.dataValue.match(/<img[\s\S]+data:/i)){b=b.data;var c=document.implementation.createHTMLDocument(""),
c=new CKEDITOR.dom.element(c.body),e=a.widgets.registered.easyimage,g=0,h,d,f,l;c.data("cke-editable",1);c.appendHtml(b.dataValue);d=c.find("img");for(l=0;l<d.count();l++){f=d.getItem(l);var k=(h=f.getAttribute("src"))&&"data:"==h.substring(0,5),m=null===f.data("cke-realelement");k&&m&&!f.isReadOnly(1)&&(g++,1<g&&(k=a.getSelection().getRanges(),k[0].enlarge(CKEDITOR.ENLARGE_ELEMENT),k[0].collapse(!1)),h.match(/image\/([a-z]+?);/i),k=e._spawnLoader(a,h,e),h=e._insertWidget(a,e,h,!1,{uploadId:k.id}),
h.data("cke-upload-id",k.id),h.replace(f))}b.dataValue=c.getHtml()}})}var m=!1;CKEDITOR.plugins.easyimage={_parseSrcSet:function(a){var b=[],c;for(c in a)"default"!==c&&b.push(a[c]+" "+c+"w");return b.join(", ")}};CKEDITOR.plugins.add("easyimage",{requires:"imagebase,balloontoolbar,button,dialog,cloudservices",lang:"en",icons:"easyimagefull,easyimageside,easyimagealt,easyimagealignleft,easyimagealigncenter,easyimagealignright",hidpi:!0,onLoad:function(){CKEDITOR.dialog.add("easyimageAlt",this.path+
"dialogs/easyimagealt.js")},init:function(a){if(!CKEDITOR.env.ie||11<=CKEDITOR.env.version)m||(CKEDITOR.document.appendStyleSheet(this.path+"styles/easyimage.css"),m=!0),a.addContentsCss&&a.addContentsCss(this.path+"styles/easyimage.css")},afterInit:function(a){if(!CKEDITOR.env.ie||11<=CKEDITOR.env.version){var b;b=CKEDITOR.tools.object.merge({full:{attributes:{"class":"easyimage-full"},label:a.lang.easyimage.commands.fullImage},side:{attributes:{"class":"easyimage-side"},label:a.lang.easyimage.commands.sideImage},
alignLeft:{attributes:{"class":"easyimage-align-left"},label:a.lang.easyimage.commands.alignLeft},alignCenter:{attributes:{"class":"easyimage-align-center"},label:a.lang.easyimage.commands.alignCenter},alignRight:{attributes:{"class":"easyimage-align-right"},label:a.lang.easyimage.commands.alignRight}},a.config.easyimage_styles);r(a,b);t(a);n(a,b);a.ui.addButton("EasyimageAlt",{label:a.lang.easyimage.commands.altText,command:"easyimageAlt",toolbar:"easyimage,3"});for(var c in b)a.ui.addButton("Easyimage"+
g(c),{label:b[c].label,command:"easyimage"+g(c),toolbar:"easyimage,99",icon:b[c].icon,iconHiDpi:b[c].iconHiDpi});p(a);b=a.config.easyimage_toolbar;a._.easyImageToolbarContext=a.balloonToolbars.create({buttons:b.join?b.join(","):b,widgets:["easyimage"]})}}});CKEDITOR.config.easyimage_class="easyimage";CKEDITOR.config.easyimage_styles={};CKEDITOR.config.easyimage_defaultStyle="full";CKEDITOR.config.easyimage_toolbar=["EasyimageFull","EasyimageSide","EasyimageAlt"]})();