/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.uos.inf.did.abbozza.plugin;

import de.uos.inf.did.abbozza.AbbozzaLocale;
import de.uos.inf.did.abbozza.AbbozzaLogger;
import de.uos.inf.did.abbozza.AbbozzaServer;
import java.awt.Color;
import java.awt.Component;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author michael
 */
public class PluginPanel extends javax.swing.JPanel implements ListCellRenderer {

    private String _name;
    protected String _url;
    private String _desc;
    private String _id;
    private PluginConfigPanel _panel;
    private boolean _selected;
    
    /**
     * Creates new form PluginPanel
     */
    public PluginPanel(String name, String url, String desc, String id, PluginConfigPanel panel, boolean selected) {
        _name = name;
        _url = url;
        _desc = desc;
        _id = id;
        _panel = panel;
        _selected = selected;
        
        initComponents();
        
        if (_selected) {
            this.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5));
        } else {
            this.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 5));
        }
        
        Plugin plugin = AbbozzaServer.getPluginManager().getPlugin(id);
        
        String text = _name + "\n\n" + _desc + "\n\n";

        if ( plugin != null ) {
            text = text + AbbozzaLocale.entry("gui.is_installed");
        }
        descPane.setBackground(Color.WHITE);
        descPane.setText(text);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descPane = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        descPane.setEditable(false);
        descPane.setColumns(20);
        descPane.setLineWrap(true);
        descPane.setRows(5);
        descPane.setText(_desc);
        descPane.setWrapStyleWord(true);
        descPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        return this;
    }
}
