/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.uos.inf.did.abbozza.monitor;

import java.awt.CardLayout;
import javax.swing.JPopupMenu;

/**
 *
 * @author mbrinkmeier
 */
public class OszillosgraphMonitor extends MonitorPanel {

    private TableMonitor tableMonitor;
    private GraphMonitor graphMonitor;
    /**
     * Creates new form OszillosgraphMonitor
     */
    public OszillosgraphMonitor() {
        tableMonitor = new TableMonitor();
        graphMonitor = new GraphMonitor(tableMonitor.getTableModel());
        initComponents();
        monitorPanel.add(tableMonitor);
        monitorPanel.add(graphMonitor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewSelect = new javax.swing.JComboBox();
        monitorPanel = new javax.swing.JPanel();

        viewSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tabelle", "Graph" }));
        viewSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSelectActionPerformed(evt);
            }
        });

        monitorPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monitorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 311, Short.MAX_VALUE)
                .addComponent(viewSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(viewSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monitorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSelectActionPerformed
        int selected = viewSelect.getSelectedIndex();
        ((CardLayout) monitorPanel.getLayout()).next(monitorPanel);
    }//GEN-LAST:event_viewSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel monitorPanel;
    private javax.swing.JComboBox viewSelect;
    // End of variables declaration//GEN-END:variables

    @Override
    public void processMessage(String s) {
        tableMonitor.processMessage(s);
        graphMonitor.processMessage(s);
    }

    @Override
    public JPopupMenu getPopUp() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getName() {
        return "";
    }
}
