/**
 * @license abbozza!
 *
 * Copyright 2015 Michael Brinkmeier ( michael.brinkmeier@uni-osnabrueck.de )
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
/**
 * @fileoverview ... @author michael.brinkmeier@uni-osnabrueck.de (Michael
 * Brinkmeier)
 */
package de.uos.inf.did.abbozza.handler;

import de.uos.inf.did.abbozza.AbbozzaLocale;
import de.uos.inf.did.abbozza.AbbozzaServer;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author mbrinkmeier
 */
public class LoadHandlerPanel extends javax.swing.JPanel implements PropertyChangeListener {

    private String system = "";
    private JFileChooser chooser;
    private String options = "{}";
    private boolean applyOptions = false;
    private String url = null;
    
    /**
     * Creates new form LoadHandlerPanel
     * 
     * @param chooser The {@link JFileChooser} used for choosing the file.
     */
    public LoadHandlerPanel(JFileChooser chooser) {
        this.chooser = chooser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        taskPathButton = new javax.swing.JButton();
        sketchbookPathButton = new javax.swing.JButton();
        webButton = new javax.swing.JButton();

        jScrollPane1.setEnabled(false);

        description.setEditable(false);
        description.setColumns(20);
        description.setRows(5);
        description.setAutoscrolls(false);
        jScrollPane1.setViewportView(description);

        taskPathButton.setText(AbbozzaLocale.entry("gui.go_to_task_path"));
        taskPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPathButtonActionPerformed(evt);
            }
        });

        sketchbookPathButton.setText(AbbozzaLocale.entry("gui.go_to_sketchbook_path"));
        sketchbookPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sketchbookPathButtonActionPerformed(evt);
            }
        });

        webButton.setText(AbbozzaLocale.entry("gui.load_from_web"));
        webButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sketchbookPathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taskPathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(webButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskPathButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sketchbookPathButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void taskPathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPathButtonActionPerformed
        chooser.setCurrentDirectory(new File(AbbozzaServer.getConfig().getTaskPath()));
    }//GEN-LAST:event_taskPathButtonActionPerformed

    private void sketchbookPathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sketchbookPathButtonActionPerformed
        chooser.setCurrentDirectory(new File(AbbozzaServer.getInstance().getSketchbookPath()));
    }//GEN-LAST:event_sketchbookPathButtonActionPerformed

    private void webButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButtonActionPerformed
        String url = JOptionPane.showInputDialog(chooser,"Enter URL");
        if ( url != null ) {
            this.url = url;
            chooser.cancelSelection();
        }
    }//GEN-LAST:event_webButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sketchbookPathButton;
    private javax.swing.JButton taskPathButton;
    private javax.swing.JButton webButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
      String fileName = evt.getPropertyName();
                      
      if (JFileChooser.DIRECTORY_CHANGED_PROPERTY.equals(fileName))
      {
          this.description.setText("");
      }

      if (JFileChooser.SELECTED_FILE_CHANGED_PROPERTY.equals(fileName))
      {
         // Extract selected file's File object.

         File file = (File) evt.getNewValue();

        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder;

          try {
              builder = factory.newDocumentBuilder();

            // Read DOM from stream
            Document xml = builder.parse(new FileInputStream(file));
            NodeList descs = xml.getElementsByTagName("description");
            if (descs.getLength() == 0 ) {
                this.description.setText("");
            } else {
                this.description.setText(descs.item(0).getTextContent());
            }
            NodeList opts = xml.getElementsByTagName("options");
            if (opts.getLength() != 0 ) {
                this.options = opts.item(0).getTextContent();
                this.applyOptions = ((Element) opts.item(0)).getAttribute("apply").equals("yes") ? true : false;
            }
            NodeList systems = xml.getElementsByTagName("system");
            if (systems.getLength() != 0 ) {
                this.system = systems.item(0).getTextContent();
            }

            // Read DOM from stream
          } catch (Exception ex) {
              this.description.setText("");
          }

       }
    }
    
    public String getSystem() {
        return this.system;
    }
    
    public String getOptions() {
        return this.options;
    }
    
    public boolean applyOptions() {
        return this.applyOptions;
    }
 
    public String getUrl() {
        return url;
    }
}
